name = "redirekt"
type = "webpack"
zone_id = "**redacted**"
account_id = "**redacted**"
routes = ["msfjarvis.dev/*", "download.msfjarvis.dev/*"]
workers_dot_dev = false
webpack_config = "webpack.config.js"
